# docker-compose.yml
version: '2.1'
networks:
  app-network:
    name: hotrotaichinh
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: "nginx:1.20.2-alpine"
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    networks:
      - app-network