# docker-compose.yml
version: '1'
networks:
    proxy:
        external:
            name: common_proxy
            
services:
    nginx:
        container_name: nginx
        image: "nginx:1.20.2-alpine"
        restart: always
        volumes:
            - ./conf.d:/etc/nginx/conf.d
        ports:
            - "80:80"
        networks:
            - proxy