# docker-compose.default.yml
version: '1'

networks:
    proxy:
        external:
            name: common_proxy

services:
    hotrotaichinh_app:
        container_name: hotrotaichinh_app
        build:
            context: ./
            dockerfile: app.dockerfile
        command: bash -c "yarn start"
        working_dir: /docker-containers
        ports:
            - "4004:4004"
        volumes:
            - .:/docker-containers:cached
            - /docker-containers/node_modules
        networks:
            - proxy