# docker-compose.default.yml
version: '1'

networks:
    proxy:
        external:
            name: common_proxy

services:
    hotrotaichinh_db:
        container_name: hotrotaichinh_db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        image: mysql:8
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=ducdv@79
            - MYSQL_USER=ducdv79
            - MYSQL_DATABASE=hotrotaichinh
        ports:
            - 3306:3306
        volumes:
            - ~/docker-containers/hotrotaichinh/mysql:/var/lib/mysql
        networks:
            - proxy

    hotrotaichinh_api:
        container_name: hotrotaichinh_api
        build:
            context: ./
            dockerfile: api.dockerfile
        working_dir: /docker-containers
        volumes:
            - .:/docker-containers:cached
        environment:
            - "DB_CONNECTION=mysql"
            - "DB_PORT=3306"
            - "DB_HOST=hotrotaichinh_db"
            - "DB_DATABASE=hotrotaichinh"
            - "DB_USERNAME=ducdv79"
            - "DB_PASSWORD=ducdv@79"
        networks:
            - proxy